### ISSUE TITLE
Instalador fácil para MacOs

### ISSUE THREAD

**Issue by yvesmedhard** [rvigo/cl#1]
Forma de instalar no MacOs sem precisar compilar.

Sugestões: 
- Brew
- App Store
- Script
- Make

**Comment by riccisa** [comment]
> Forma de instalar no MacOs sem precisar compilar.
> 
> Sugestões:
> 
> * Brew
> * App Store
> * Script
> * Make

I had problems to install it in my mac following the steps in README.
My configuration is:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2,6 GHz

**Comment by rvigo** [comment]
Guys, the application now can be installed using `homebrew` doing the follow

``` bash 
# add the app tap
brew tap rvigo/cl
# install the app
brew install cl
```
 
If you have previously compiled the project from the source (the current install process), please delete the `cl` bin file from $HOME/.cargo/bin

Can you guys validate this process?
If everything is ok I'll close this PR and add the instructions in the README.md file.

**Comment by riccisa** [comment]
Everything is working now!
Thanks.
